build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4.3
      tests:
        override:
          - php-scrutinizer-run

checks:
    php: true
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
